//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisParkTD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametros
    {
        public int IDParametro { get; set; }
        public string NombreParametro { get; set; }
        public int ValorParametro { get; set; }
        public string DescripcionParametro { get; set; }
    }
}
