//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisParkTD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Tickets
    {
        public int IDTicket { get; set; }
        [Required]
        public int IDVehiculo { get; set; }
        [Required]
        public int IDEstadoDeTicket { get; set; }
        [Required]
        public int IDParcela { get; set; }
        [Required]
        public System.DateTime HorarioDeLlegada { get; set; }
        public Nullable<System.DateTime> HorarioDeSalida { get; set; }
        public Nullable<decimal> TiempoTotal { get; set; }
        public Nullable<decimal> PrecioTotal { get; set; }
    
        public virtual EstadosDeTicket EstadosDeTicket { get; set; }
        public virtual Parcelas Parcelas { get; set; }
        public virtual Vehiculos Vehiculos { get; set; }
    }
}
