//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisParkTD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditoriasLog
    {
        public int IDAuditoriaLog { get; set; }
        public string NombreDeUsuario { get; set; }
        public string Accion { get; set; }
        public System.DateTime FechaYHora { get; set; }
        public string IP { get; set; }
    }
}
