//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisParkTD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sisparkdbEntities : DbContext
    {
        public sisparkdbEntities()
            : base("name=sisparkdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Acciones> Acciones { get; set; }
        public virtual DbSet<AuditoriasLog> AuditoriasLog { get; set; }
        public virtual DbSet<AuditoriasTicket> AuditoriasTicket { get; set; }
        public virtual DbSet<EstadosDeTicket> EstadosDeTicket { get; set; }
        public virtual DbSet<Parcelas> Parcelas { get; set; }
        public virtual DbSet<Permisos> Permisos { get; set; }
        public virtual DbSet<Recursos> Recursos { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Tickets> Tickets { get; set; }
        public virtual DbSet<TiposDeVehiculo> TiposDeVehiculo { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Vehiculos> Vehiculos { get; set; }
        public virtual DbSet<Parametros> Parametros { get; set; }
        public virtual DbSet<Tamaños> Tamaños { get; set; }
    }
}
